/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.muzraf.hate;

public final class R {
  public static final class id {
    public static final int text_time=0x7f010000;
    public static final int text_time_value=0x7f010001;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
}